package org.example.web.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * Page controller for demonstrating the use of template engines with Spring MVC.
 */
@Controller
public class TemplateController
{
  /**
   * Displays a page generated by a PHP script.
   */
  @RequestMapping(method = RequestMethod.GET, value = "/php")
  public String php()
  {
    return "php/template";
  }
}
